version: '3'

services:
#NGINX
  nginx:
    build: ./nginx/
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - www-duck-data:/var/www/html
    networks:
      - duck
    depends_on:
      - wordpress

#WordPress
  wordpress:
    build: ./wordpress/

    restart: on-failure
    volumes:
      - www-duck-data:/var/www/html
    networks:
      - duck
    expose:
      - 9000
    entrypoint: "/bin/bash -c php-fpm7.3"

# [17-Nov-2022 16:35:09] ERROR: [/etc/php/7.3/fpm/pool.d/wordpress_pool.conf:1] value is NULL for a ZEND_INI_PARSER_ENTRY
# [17-Nov-2022 16:35:09] ERROR: Unable to include /etc/php/7.3/fpm/pool.d/wordpress_pool.conf from /etc/php/7.3/fpm/php-fpm.conf at line 1
# [17-Nov-2022 16:35:09] ERROR: failed to load configuration file '/etc/php/7.3/fpm/php-fpm.conf'
# [17-Nov-2022 16:35:09] ERROR: FPM initialization failed

  #   # environment:
  #   #   WORDPRESS_DB_HOST: mariadb:3306
  #   #   WORDPRESS_DB_USER: superPowerRanger
  #   #   WORDPRESS_DB_PASSWORD: password
  #   networks:
  #     - wp-net
    
# #MARIADB
#   mariadb:
#     image: mysql:5.7
#     volumes:
#       - data-db:/var/lib/mysql
#     restart: always
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: "password"
#       MYSQL_DATABASE: "wp"
#       MYSQL_DATABASE_USER: "superPowerRanger"
#       MYSQL_PASSWORD: "password"
#     networks:
#       - wp-net
  
networks:
  duck:
#   wp-net:
  # webserver: {}
  # database: {}

volumes:
  www-duck-data:
        # driver: host
        # driver_opts:
        #     source: /Home/ann/data
#I need to figure out how to define the path of the host mount
