version: '3'

services:
# NGINX
  nginx:
    build: ./nginx/
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - www-duck-data:/var/www/html
    networks:
      - duck
    depends_on:
      - wordpress

# WordPress
  wordpress:
    build: ./wordpress/
    restart: on-failure
    volumes:
      - www-duck-data:/var/www/html
      - db-duck-data:/var/lib/mysql
    networks:
      - duck
      - turtle
    expose:
      - 9000
    command: "'service php7.3-fpm start && tail -f /dev/null'"
    entrypoint: "/bin/sh -c"

  #   # environment:
  #   #   WORDPRESS_DB_HOST: mariadb:3306
  #   #   WORDPRESS_DB_USER: superPowerRanger
  #   #   WORDPRESS_DB_PASSWORD: password

# MARIADB
  mariadb:
    build: ./mariadb
    volumes:
      - db-duck-data:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env
    expose:
      - 3306  
    environment:
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
      # MARIADB_DATABASE: "${MARIADB_DATABASE}"
      # MARIADB_USER: "${MARIADB_USER}"
      # MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
    networks:
      - turtle
    command: "'service mysql start && mysql -uroot -ppassword < init.sql && tail -f /var/log/mysql/error.log'"
    entrypoint: "/bin/sh -c"

networks:
# frontend
  duck:
# backend
  turtle:

volumes:
  www-duck-data:
  db-duck-data:
        # driver: host
        # driver_opts:
        #     source: /Home/ann/data
#I need to figure out how to define the path of the host mount
