version: '3'

services:
# NGINX
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - www-duck-data:/var/www/html
    networks:
      - duck
    depends_on:
      - wordpress

# WordPress
  wordpress:
    build: ./requirements/wordpress/
    restart: on-failure
    volumes:
      - www-duck-data:/var/www/html
      - db-duck-data:/var/lib/mysql
    networks:
      - duck
      - turtle
    expose:
      - 9000
    env_file:
      - .env
    command: "'service php7.3-fpm start   && \
               bash init.sh ${WP_DBNAME} ${WP_DBPASS} ${WP_DBUSER} ${WP_DBHOST} && \
               tail -f /dev/null'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - mariadb

# MARIADB
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - db-duck-data:/var/lib/mysql
    restart: on-failure
    env_file:
      - .env
    expose:
      - 3306
    networks:
      - turtle
    command: "'service mysql start && \
              tail -f /var/log/mysql/error.log'"
    entrypoint: "/bin/sh -c"

networks:
# frontend
  duck:

# backend
  turtle:

volumes:
  www-duck-data:
  db-duck-data:
    # driver: local
    # driver_opts:
    #   type: 'volume'  
    #   o: 'bind'
    #   device: '/home/ann/data/db-duck-data-volume'
