version: "3.9"

services:
# NGINX
  nginx:
    build: ./requirements/nginx/
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - duck
    volumes:
      - www-duck-data:/var/www/html
    command: "'bash init.sh'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - wordpress

# WordPress
  wordpress:
    build: ./requirements/wordpress/
    restart: on-failure
    networks:
      - duck
      - turtle
    volumes:
      - www-duck-data:/var/www/html
      - db-duck-data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 9000
  command: "' /bin/sleep 5 && \
              bash init.sh && \
              php-fpm7.3 --nodaemonize -R'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - mariadb

# Mariadb
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    restart: on-failure
    networks:
      - turtle
    volumes:
      - db-duck-data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    command: "'mysqld'"
    entrypoint: "/bin/sh -c"

networks:
  duck: #frontend
  turtle: # backend

volumes:
  www-duck-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/www_volume
  db-duck-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db_volume
