version: '3'

services:
# NGINX
  nginx:
    build: ./requirements/nginx/
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - duck
    volumes:
      - www-duck-data:/var/www/html
    depends_on:
      - wordpress

# WordPress
  wordpress:
    build:
      context: ./requirements/wordpress/
      args:
        BONUS: one
    restart: on-failure
    networks:
      - duck
      - turtle
      # - bonus
    volumes:
      - www-duck-data:/var/www/html
      - db-duck-data:/var/lib/mysql
    env_file:
      - .env

    expose:
      - 9000
    command:
      "'  /bin/sleep 5 && \
          bash init.sh bonus && \ 
          php-fpm7.3 --nodaemonize -R'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - mariadb

# Mariadb
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    restart: on-failure
    networks:
      - turtle
    volumes:
      - db-duck-data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    command: "'mysqld'"
    entrypoint: "/bin/sh -c"

# redis
  redis:
    # container_name: srcs-redis-1
    build: ./requirements/bonus/redis/
    restart: on-failure
    expose:
      - 6379
    networks:
      - bonus
    command: "'redis-server /etc/redis/redis.conf && tail -f /dev/null'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - wordpress

# ftp service
  ftp:
    build:
      context: ./requirements/bonus/ftp/
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    restart: on-failure
    env_file:
      - .env
    volumes:
      - www-duck-data:/var/www/html
    ports:
      - "21:21"
    command: "'bash init.sh && vsftpd'"
    entrypoint: "/bin/sh -c"

# devcontainer
  dev:
    build: ./requirements/bonus/dev/
    restart: on-failure
    command: "systemd"
    env_file:
      - .env
    volumes:
      - ${WORK_DIR}:/home/devcontainer/

networks:
  duck: #frontend
  turtle: #backend
  # bonus: #bonus redis

volumes:
# WP website files volume
  www-duck-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ann/data/www_volume
# Database 
  db-duck-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ann/data/db_volume
# # bonus volumes
#   dev-data:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /home/ann/data/dev_volume
