version: '3.9'

services:
# NGINX
  nginx:
    build: ./../nginx/
    image: nginx
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - duck
    volumes:
      - www-duck-data:/var/www/html
    command: "'bash init.sh'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - wordpress

# WordPress
  wordpress:
    build:
      context: ./../wordpress/
      args:
        BONUS: one
    image: wordpress
    restart: on-failure
    networks:
      - duck
      - turtle
      - bonus
    volumes:
      - www-duck-data:/var/www/html
      - db-duck-data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 9000
    command:
      "'  bash init.sh bonus && \ 
          php-fpm7.3 --nodaemonize -R'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - mariadb
      - redis

# Mariadb
  mariadb:
    build:
      context: ./../mariadb/
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    image: mariadb
    restart: on-failure
    networks:
      - turtle
    volumes:
      - db-duck-data:/var/lib/mysql
    env_file:
      - .env
    expose:
      - 3306
    command: "'mysqld'"
    entrypoint: "/bin/sh -c"

# redis
  redis:
    build: ./redis/
    image: redis
    restart: on-failure
    expose:
      - 6379
    networks:
      - bonus
    command: "'echo \"Initializing redis\" && \
               sed -i \"s/bind 127.0.0.1 ::1/#bind 127.0.0.1 ::1/g\" /etc/redis/redis.conf && \
               sed -i \"s/protected-mode yes/protected-mode no/g\" /etc/redis/redis.conf && \
               redis-server --protected-mode no'" #" && \
    entrypoint: "/bin/sh -c"

# ftp service
  ftp:
    build:
      context: ./ftp/
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    image: ftp
    restart: on-failure
    env_file:
      - .env
    volumes:
      - www-duck-data:/var/www/html
    ports:
      - "20-21:20-21"
      - "990:990"
      - "65000-65042:65000-65042"
    command: "'vsftpd'"
    depends_on:
      - wordpress
    entrypoint: "/bin/sh -c"

# redis-commander
  redis-commander:
    build: ./redis-commander/
    image: redis-commander
    restart: on-failure
    ports:
      - "8081:8081"
    networks:
      - bonus
    # environment:
    #   - REDIS_HOSTS=local:bonus-redis-1:6379
    #   - HTTP_USER=urnotgonnaguess
    #   - HTTP_PASS=udid
    command: "'redis-commander --redis-host='bonus-redis-1' --redis-port=6379 \
               --http-u=urnotgonnaguess --http-p=udid'"
    entrypoint: "/bin/sh -c"
    depends_on:
      - redis

# devcontainer
  dev:
    build: ./dev/
    image: dev
    restart: on-failure
    command: "systemd"
    env_file:
      - .env
    volumes:
      - /${WORK_DIR}:/home/devcontainer/

networks:
  duck: #frontend
  turtle: #backend
  bonus: #bonus redis

volumes:
  www-duck-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/www_volume
  db-duck-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db_volume
